export const GET_ALL_PHONES_REQUEST = "GET_ALL_PHONES_REQUEST";
export const GET_ALL_PHONES_SUCCESS = "GET_ALL_PHONES_SUCCESS";
export const GET_ALL_PHONES_FAILURE = "GET_ALL_PHONES_FAILURE";
export const GET_PHONE_REQUEST = "GET_PHONE_REQUEST";
export const GET_PHONE_SUCCESS = "GET_PHONE_SUCCESS";
export const GET_PHONE_FAILURE = "GET_PHONE_FAILURE";
